use yth_alarm;
-- ----------------------------
-- Records of dict
-- ----------------------------
truncate table dict;
INSERT INTO `dict` VALUES ('sour_obj', '1', '涉密终端', '1', '泄密-来源-分类', '内部网络', null, '1', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '2', '办公终端', '2', '泄密-来源-分类', '内部网络', null, '1', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '3', '非密数据库', '3', '泄密-来源-分类', '内部网络', null, '2', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '4', '门户网站', '4', '泄密-来源-分类', '内部网络', null, '3', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '5', '网页发布', 'Http', '泄密-来源-分类', '内部网络', null, '4', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '6', '即时通讯', 'Im', '泄密-来源-分类', '外部网络', null, '2', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '7', '网盘', 'Netdisk', '泄密-来源-分类', '外部网络', null, '2', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '8', '邮件', 'Email', '泄密-来源-分类', '外部网络', null, '3', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '9', 'FTP', 'Filetransfer', '泄密-来源-分类', '外部网络', null, '4', null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj', '10', '其他', 'Other', '泄密-来源-分类', '外部网络', null, '5', null, null, null, null);
INSERT INTO `dict` VALUES ('GJQM_unknown_subtype', '1', '异常私有协议', null, '攻击-异常-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('GJQM_unknown_subtype', '2', '可疑心跳保活', null, '攻击-异常-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('GJQM_unknown_subtype', '3', '异常通用代理', null, '攻击-异常-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('GJQM_unknown_subtype', '4', '远程控制', null, '攻击-异常-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_type', '1', '涉密终端', null, '资产-资产类型', null, null, '台', 'icon-wangpan', null, '泄密终端', 'show');
INSERT INTO `dict` VALUES ('assets_type', '2', '办公终端', null, '资产-资产类型', null, null, '台', 'icon-wangpan', null, '办公终端', 'show');
INSERT INTO `dict` VALUES ('assets_type', '3', '非密数据库', null, '资产-资产类型', null, null, '个', 'icon-wangpan', null, '监控终端', 'show');
INSERT INTO `dict` VALUES ('assets_type', '4', '门户网站', null, '资产-资产类型', null, null, '个', 'icon-wangpan', null, '门户网站', 'hide');
INSERT INTO `dict` VALUES ('assets_type', '5', '检测器', null, '资产-资产类型', null, null, '台', 'icon-wangpan', null, '检测器', 'hide');
INSERT INTO `dict` VALUES ('account_type', '1', 'FTP', null, '资产-账号资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type', '2', '邮件', null, '资产-账号资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type', '3', '即时通讯', null, '资产-账号资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type', '4', '博客', null, '资产-账号资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type', '5', '论坛', null, '资产-账号资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type', '6', '网盘', null, '资产-账号资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_data_type', '1', '门户网站采集量', null, '资产—数据资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_data_type', '2', '机关口镜像数据量', null, '资产—数据资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_data_type', '3', '数据库采集量', null, '资产—数据资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_data_type', '4', '告警采集量', null, '资产—数据资产-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('chuzhi_status', '0', '未判定', null, '处置（判定）状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('chuzhi_status', '1', '已判定违规', null, '处置（判定）状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('chuzhi_status', '2', '已完成', null, '处置状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_level', '1', '秘密', null, '事件等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_level', '2', '机密', null, '事件等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_level', '3', '绝密', null, '事件等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '1', 'FTP文件传输', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '2', 'QQ文件', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '3', '网易邮箱', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '4', '论坛', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '5', 'QQ邮箱', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '6', '门户网站', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '7', '百度网盘', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '8', '博客', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '9', '163', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('sour_obj_sub', '10', '微信', null, '泄密-泄密来源子类', null, 'sour_obj', null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_file_type', '1', '文档类', null, '资产-文件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_file_type', '2', '网页', null, '资产-文件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_file_type', '3', '测绘', null, '资产-文件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_file_type', '4', '图片', null, '资产-文件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_file_type', '5', '压缩包', null, '资产-文件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_file_type', '6', '其他', null, '资产-文件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('important_assets_type', '1', 'IP', null, '重点资产类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('important_assets_type', '2', '域名', null, '重点资产类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('important_assets_type', '3', 'URL', null, '重点资产类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('important_assets_type', '4', '账号', null, '重点资产类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_level', '1', '无风险', null, '告警等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_level', '2', '一般级', null, '告警等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_level', '3', '关注级', null, '告警等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_level', '4', '严重级', null, '告警等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_level', '5', '紧急级', null, '告警等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '7', '门户告警', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '2', '标密文件', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '1', '电子密标文件', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '3', '关键字', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '4', '加密文件', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '5', '多层压缩', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '6', '图片', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '8', '版式文件', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '9', '违规存储', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('wgxw_type', '10', '违规外联', null, '泄密-违规行为-类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('damage_level', '1', '严重', null, '危害等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('damage_level', '2', '一般', null, '危害等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('damage_level', '3', '轻微', null, '危害等级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_status', '1', '启用', null, '资产状态', null, '1', 'normal', null, null, null, null);
INSERT INTO `dict` VALUES ('assets_status', '2', '禁用', null, '资产状态', null, '1', 'error', null, null, null, null);
INSERT INTO `dict` VALUES ('assets_status', '3', '运行', null, '资产状态', null, '2', 'normal', null, null, null, null);
INSERT INTO `dict` VALUES ('account_type_sub', '1', '雅虎邮箱', null, '资产—账号资产-子类型', null, 'account_type', null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type_sub', '2', '163邮箱', null, '资产—账号资产-子类型', null, 'account_type', null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type_sub', '3', '谷歌邮箱', null, '资产—账号资产-子类型', null, 'account_type', null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type_sub', '4', '微信', null, '资产—账号资产-子类型', null, 'account_type', null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type_sub', '5', 'qq', null, '资产—账号资产-子类型', null, 'account_type', null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_type', '1', '违规外联', null, '事件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_type', '2', '互联网传输泄密', ' ', '事件类型', ' ', ' ', ' ', ' ', ' ', ' ', ' ');
INSERT INTO `dict` VALUES ('event_type', '3', '网络攻击窃密', null, '事件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_type', '4', '违规存储/处理涉密信息', null, '事件类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type_sub', '6', '阿里云邮箱', null, '资产—账号资产-子类型', null, 'account_type', null, null, null, null, null);
INSERT INTO `dict` VALUES ('account_type_sub', '7', 'qq邮箱', null, '资产—账号资产-子类型', null, 'account_type', null, null, null, null, null);
INSERT INTO `dict` VALUES ('platform', '1', '保密监测平台', '保密监测平台', '056', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('platform', '2', '涉密计算机及移动存储介质保密管理系统', '涉密计算机及移动存储介质保密管理系统', '3合1', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('platform', '3', '文档审计系统', '互联网文档操作安全审计系统', '文', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('platform', '4', '互联网门户网站保密检查平台', '互联网门户网站保密检查平台', '门', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('deepana_status', '0', '未分析', null, '深度分析状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('deepana_status', '1', '已分析', null, '深度分析状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('assets_status', '4', '停止', '', '资产状态', '', '2', 'error', '', '', '', '');
INSERT INTO `dict` VALUES ('logex_log_type', '1', '违规外联日志', null, '三合一违规外联日志类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('logex_log_type', '2', '优盘使用日志', null, '三合一违规外联日志类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('logex_log_type', '3', '单向导入日志', null, '三合一违规外联日志类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '1', 'Http', '网页发布', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '2', 'Im', '即时通讯', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '3', 'Netdisk', '网盘', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '4', 'Email', '电子邮件', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '5', 'Filetransfer', '文件传输', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '6', 'Other', '其他', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '7', 'csmp', '接入互联网', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '8', 'docaudit', '文档操作', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('actiontype', '9', 'website', '门户网站', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('cz_status', '1', 'NO', '未处置', null, null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('cz_status', '2', 'PASS', '正常', '处置状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('cz_status', '3', 'JIMI', '机密', '处置状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('cz_status', '4', 'MIMI', '秘密', '处置状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('cz_status', '5', 'JUEMI', '绝密', '处置状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('cz_status', '6', 'NEIBU', '内部', '处置状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_miji', '3', 'JIMI', '机密', '事件密级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_miji', '4', 'MIMI', '秘密', '事件密级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_miji', '5', 'JUEMI', '绝密', '事件密级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_miji', '6', 'NEIBU', '内部', '事件密级', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_status', '1', '', '待处理', '事件状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_status', '2', null, '不移交', '事件状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_status', '3', null, '移交未反馈', '事件状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('event_status', '4', null, '移交已反馈', '事件状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_type', '1', '违规外联', null, '告警分类', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_type', '2', '文档涉密', null, '告警分类', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_type', '3', '攻击告警', null, '告警分类', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('alarm_type', '4', '保密合规', null, '告警分类', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('keytype', '1', '关键字', null, '关键字分类', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('keytype', '2', '正则表达式', null, '关键字分类', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('operation_type', '1', '打开文件告警', null, '文档审计操作类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('operation_type', '2', '复制文件告警', null, '文档审计操作类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('operation_type', '3', '修改文件告警', null, '文档审计操作类型', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('translate_code', '\"', '转为', '%&*', '转译字符', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('translate_code', '\'', '转为', '*&%', '转译字符', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('translate_code', '\\', '转为', '$#^', '转译字符', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('translate_code', '/', '转为', '^#$', '转译字符', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('client_status', '0', '客户端离线', null, '文档审计客户端在线状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('client_status', '1', '客户端在线', null, '文档审计客户端在线状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('client_status', '2', '客户端服务器卸载', null, '文档审计客户端在线状态', null, null, null, null, null, null, null);
INSERT INTO `dict` VALUES ('client_status', '3', '客户端终端卸载', null, '文档审计客户端在线状态', null, null, null, null, null, null, null);
INSERT INTO `yth_alarm`.`dict` (`key`, `value`, `desc`, `name`, `remark`, `group`, `parent_key`, `optional_1`, `optional_2`, `optional_3`, `optional_4`, `optional_5`) VALUES ('platform', '5', '网络数据库保密检查平台', '网络数据库保密检查平台', '数', NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO `yth_alarm`.`dict` (`key`, `value`, `desc`, `name`, `remark`, `group`, `parent_key`, `optional_1`, `optional_2`, `optional_3`, `optional_4`, `optional_5`) VALUES ('actiontype', '10', 'dbcheck', '数据库存储', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);



truncate table cfg_keyword;
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"内部资料"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"不予公开"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"内部资料不予公开"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"知悉范围"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"会后回收"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"注意保密"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"不予外传"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"只发至县团级"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"只发至省部级"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"中发"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"厅发"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"国办发"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"中办发"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"中发《"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('"舆"', 3, '1', '', 'sysadmin', Now(), '1');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('^中共中央.+?意见$', 3, '1', '', 'sysadmin', Now(), '2');
insert into cfg_keyword(`keyword`, `keylevel` ,`enabled`,  `remark`,  `add_user`,  `add_time` ,  `keytype`) VALUES ('^关于.+?立案查处$', 3, '1', '', 'sysadmin', Now(), '2');

